### ISSUE TITLE
TBRBuffer.Remove fails with aByteIndex=0 and aLength=(the size of the buffer)

### ISSUE THREAD

**Issue by teo-tsirpanis** [quartexNOR/byterage#1]
As stated before, there is a bug in the Remove method of the TBRBuffer class.
If parameter aButeIndex is zero and parameter aLength is the size of the buffer, no operation is done and the buffer's content remain the same.

I have found a solution to this problem, but I cannot provide a pull request. Instead, I will give a screenshot.

![image](https://cloud.githubusercontent.com/assets/12659251/9428442/0ed97196-49b7-11e5-8e20-6f3e4857d206.png)

**Comment by quartexNOR** [comment]
This has been fixed quite some time ago. However, since this code (as well as pixelrage) was taken by PilotLogic, renamed and basically miss-represented as their own, I will no longer publish code like this. But thank you for pointing out the bug!
